# Site settings
title: Y. Miles Zhang
email: yuanmeng.zhang@ufl.edu
url: https://ymilesz.github.io
author: YMZ

# Color settings (hex-codes without the leading hash-tag)
color:
  link: 0021a5
  primary: fa4616
  secondary: fa4616
  secondary-dark: 000
  dark: 000

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ymilesz
  - title: google scholar 
    url: https://scholar.google.com/citations?user=kUZTyoQAAAAJ&hl=en
  - title: researchgate
    url: https://www.researchgate.net/profile/Yuanmeng_Zhang
    
# Build settings
markdown: kramdown
permalink: pretty

##Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-twitter-plugin
